select distinct ID_TIPO_BIBLIOGRAFIA tipo, AUTOR, PUBLICACION,TITULO, CAMPO_1, CAMPO_2, CAMPO_3, CAMPO_4, TEMAS_RECOMIENDA
from TD_BIBLIOGRAFIA
where ID_SOLICITUD = :id_asignatura
and ES_COMPLEMENTARIA = 0
order by AUTOR