SELECT DISTINCT
       b.ID_TIPO_BIBLIOGRAFIA AS tipo,
       b.AUTOR,
       b.PUBLICACION,
       b.TITULO,
       b.CAMPO_1,
       b.CAMPO_2,
       b.CAMPO_3,
       b.CAMPO_4,
       b.TEMAS_RECOMIENDA
  FROM SIPEFI.TD_BIBLIOGRAFIA b
  INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
    ON s.ID_SOLICITUD = b.ID_SOLICITUD
   AND s.ID_ESTATUS_SOLICITUD = b.ID_ESTATUS_SOLICITUD
 WHERE b.ID_SOLICITUD = :id_asignatura
   AND s.HISTORICA = 0
   AND s.ID_ESTATUS_SOLICITUD <> 0
   AND b.ES_COMPLEMENTARIA = 1
 ORDER BY b.AUTOR
