with RELACION_lICENCIATURA_ASIGNATURA as (
    SELECT distinct
        rel.ID_LICENCIATURA,
        rel.ID_SOLICITUD,
        rel.ID_CARACTER_ASIG,
        min(rel.SEMESTRE) SEMESTRE
    from SIPEFI.TD_REL_LIC_ASIGNATURA rel
    where rel.ID_LICENCIATURA = :id_licenciatura
    group by rel.ID_LICENCIATURA, rel.ID_SOLICITUD, rel.ID_CARACTER_ASIG
)
SELECT a.ID_ASIGNATURA
from SIPEFI.TD_ASIGNATURA a,
     SIPEFI.TD_SOLICITUD_TOMO_II s,
     RELACION_lICENCIATURA_ASIGNATURA l
where a.ID_ASIGNATURA = s.ID_SOLICITUD
  and l.ID_SOLICITUD = a.ID_ASIGNATURA
  and l.id_caracter_asig = :caracter
  and s.HISTORICA != 1
ORDER BY L.SEMESTRE, a.ASIGNATURA