WITH SOLICITUD_ACTIVA AS (
    SELECT s.ID_SOLICITUD,
           s.ID_ESTATUS_SOLICITUD
      FROM SIPEFI.TD_SOLICITUD_TOMO_II s
     WHERE s.ID_SOLICITUD = :id_asignatura
       AND s.HISTORICA = 0
       AND s.ID_ESTATUS_SOLICITUD <> 0
),
VALOR_PRACTICO AS (
    SELECT LISTAGG(cvp.VALOR_PRACTICO, ', ')
           WITHIN GROUP (ORDER BY cvp.VALOR_PRACTICO) AS valor_practico
      FROM CATALOGO.TC_VALOR_PRACTICO cvp
      INNER JOIN SIPEFI.TD_REL_VAL_PRACTICO rvp
        ON cvp.ID_VALOR_PRACTICO = rvp.ID_VALOR_PRACTICO
      INNER JOIN SOLICITUD_ACTIVA sa
        ON sa.ID_SOLICITUD = rvp.ID_SOLICITUD
       AND sa.ID_ESTATUS_SOLICITUD = rvp.ID_ESTATUS_SOLICITUD
),
SEMESTRE AS (
    SELECT LISTAGG(DISTINCT rel.SEMESTRE, ', ')
           WITHIN GROUP (ORDER BY rel.SEMESTRE) AS SEMESTRE
      FROM SIPEFI.TD_REL_LIC_ASIGNATURA rel
      INNER JOIN SOLICITUD_ACTIVA sa
        ON sa.ID_SOLICITUD = rel.ID_SOLICITUD
       AND sa.ID_ESTATUS_SOLICITUD = rel.ID_ESTATUS_SOLICITUD
     WHERE rel.ID_LICENCIATURA = :id_licenciatura
),
COLOR AS (
    SELECT '#FFD400' AS color, 1 AS id FROM dual
    UNION ALL SELECT '#5DBE63', 2 FROM dual
    UNION ALL SELECT '#BDA982', 3 FROM dual
    UNION ALL SELECT '#4DC8E7', 4 FROM dual
    UNION ALL SELECT '#4F617C', 5 FROM dual
    UNION ALL SELECT '#AC92C5', 6 FROM dual
    UNION ALL SELECT '#F07B22', 7 FROM dual
)
SELECT DISTINCT
       l.licenciatura,
       a.ASIGNATURA,
       s.CLAVE_ASIGNATURA,
       SEMESTRE.SEMESTRE,
       s.CREDITOS,
       ar.AREA_CONOCIMIENTO,
       m.MODALIDAD,
       tm.TIPO_MODALIDAD,
       c.CARACTER_ASIGNATURA,
       VALOR_PRACTICO.valor_practico,
       s.HORAS_TEO_SEMANA,
       s.HORAS_PRACT_SEMANA,
       s.HORAS_TEO_SEMESTRE,
       s.HORAS_PRACT_SEMESTRE,
       TO_CHAR(s.OBJETIVO_GENERAL),
       s.FORMACION_INTEGRAL,
       s.PERFIL_PROFESIOGRAFICO,
       cl.color
  FROM SOLICITUD_ACTIVA sa
  INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
    ON s.ID_SOLICITUD = sa.ID_SOLICITUD
   AND s.ID_ESTATUS_SOLICITUD = sa.ID_ESTATUS_SOLICITUD
  INNER JOIN SIPEFI.TD_ASIGNATURA a
    ON a.ID_ASIGNATURA = s.ID_SOLICITUD
  INNER JOIN SIPEFI.TD_REL_LIC_ASIGNATURA rla
    ON rla.ID_SOLICITUD = sa.ID_SOLICITUD
   AND rla.ID_ESTATUS_SOLICITUD = sa.ID_ESTATUS_SOLICITUD
   AND rla.ID_LICENCIATURA = :id_licenciatura
  INNER JOIN CATALOGO.TC_LICENCIATURA l
    ON l.ID_LICENCIATURA = rla.ID_LICENCIATURA
  INNER JOIN CATALOGO.TC_AREA_CONOCIMIENTO ar
    ON ar.ID_AREA_CONOCIMIENTO = rla.ID_AREA_CONOCIMIENTO
  INNER JOIN CATALOGO.TC_MODALIDAD m
    ON m.ID_MODALIDAD = s.ID_MODALIDAD
  INNER JOIN CATALOGO.TC_TIPO_MODALIDAD tm
    ON tm.ID_TIPO_MODALIDAD = s.ID_TIPO_MODALIDAD
  INNER JOIN CATALOGO.TC_CARACTER_ASIGNATURA c
    ON c.ID_CARACTER_ASIG = rla.ID_CARACTER_ASIG
  INNER JOIN COLOR cl
    ON cl.id = rla.ID_AREA_CONOCIMIENTO
 CROSS JOIN VALOR_PRACTICO
 CROSS JOIN SEMESTRE
