WITH RELACION_LICENCIATURA_ASIGNATURA AS (
    SELECT rel.ID_LICENCIATURA,
           rel.ID_SOLICITUD,
           rel.ID_CARACTER_ASIG,
           MIN(rel.SEMESTRE) AS SEMESTRE
      FROM SIPEFI.TD_REL_LIC_ASIGNATURA rel
      INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
        ON s.ID_SOLICITUD = rel.ID_SOLICITUD
       AND s.ID_ESTATUS_SOLICITUD = rel.ID_ESTATUS_SOLICITUD
     WHERE rel.ID_LICENCIATURA = :id_licenciatura
       AND s.HISTORICA = 0
       AND s.ID_ESTATUS_SOLICITUD <> 0
     GROUP BY rel.ID_LICENCIATURA,
              rel.ID_SOLICITUD,
              rel.ID_CARACTER_ASIG
)
SELECT a.ID_ASIGNATURA
  FROM SIPEFI.TD_ASIGNATURA a
  INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
    ON s.ID_SOLICITUD = a.ID_ASIGNATURA
  INNER JOIN RELACION_LICENCIATURA_ASIGNATURA l
    ON l.ID_SOLICITUD = a.ID_ASIGNATURA
 WHERE l.ID_CARACTER_ASIG = :caracter
   AND s.HISTORICA = 0
   AND s.ID_ESTATUS_SOLICITUD <> 0
 ORDER BY l.SEMESTRE, a.ASIGNATURA
