--SELECT distinct a.ID_ASIGNATURA, l.ID_LICENCIATURA, l.SEMESTRE, a.ASIGNATURA
SELECT distinct a.ID_ASIGNATURA
from SIPEFI.TD_ASIGNATURA a,
              SIPEFI.TD_SOLICITUD_TOMO_II s,
              SIPEFI.TD_REL_LIC_ASIGNATURA l
where a.ID_ASIGNATURA = s.ID_SOLICITUD
  and l.ID_SOLICITUD = a.ID_ASIGNATURA
  and s.HISTORICA != 1
  and l.ID_LICENCIATURA = :id_licenciatura
ORDER BY L.SEMESTRE, a.ASIGNATURA