--ALTER SESSION SET CURRENT_SCHEMA = SIPEFI;
with VALOR_PRACTICO as (
    SELECT LISTAGG(cvp.VALOR_PRACTICO, ', ') WITHIN GROUP (ORDER BY cvp.VALOR_PRACTICO) as valor_practico
    from CATALOGO.TC_VALOR_PRACTICO cvp,
         SIPEFI.TD_REL_VAL_PRACTICO rvp
    where cvp.ID_VALOR_PRACTICO = rvp.ID_VALOR_PRACTICO
      and rvp.ID_SOLICITUD = :id_asignatura
 ), SEMESTRE AS (
         select  LISTAGG(distinct s.SEMESTRE, ', ') WITHIN GROUP (ORDER BY s.SEMESTRE) as SEMESTRE
        FROM SIPEFI.TD_ASIGNATURA a,
             SIPEFI.TD_REL_LIC_ASIGNATURA s
        WHERE s.ID_LICENCIATURA = :id_licenciatura
          and s.ID_SOLICITUD = :id_asignatura
 ), COLOR AS (
    SELECT '#FFD400'   AS color, 1 AS id FROM dual
    UNION ALL
    SELECT '#5DBE63', 2 FROM dual
    UNION ALL
    SELECT '#BDA982',  3 FROM dual
    UNION ALL
    SELECT '#4DC8E7', 4 FROM dual
    UNION ALL
    SELECT '#4F617C', 5 FROM dual
    UNION ALL
    SELECT '#AC92C5', 6 FROM dual
    UNION ALL
    SELECT '#F07B22', 7 FROM dual
)
SELECT distinct l.licenciatura, a.ASIGNATURA, s.CLAVE_ASIGNATURA, SEMESTRE.SEMESTRE, s.CREDITOS, ar.AREA_CONOCIMIENTO,
                m.MODALIDAD, tm.TIPO_MODALIDAD, c.CARACTER_ASIGNATURA, VALOR_PRACTICO.valor_practico, s.HORAS_TEO_SEMANA,
                s.HORAS_PRACT_SEMANA,s.HORAS_TEO_SEMESTRE, s.HORAS_PRACT_SEMESTRE, to_char(s.OBJETIVO_GENERAL),
                s.FORMACION_INTEGRAL, s.PERFIL_PROFESIOGRAFICO, cl.color
FROM CATALOGO.TC_LICENCIATURA l,
     CATALOGO.TC_AREA_CONOCIMIENTO ar,
     CATALOGO.TC_MODALIDAD m,
     CATALOGO.TC_TIPO_MODALIDAD tm,
     CATALOGO.TC_CARACTER_ASIGNATURA c,
     SIPEFI.TD_ASIGNATURA a,
     SIPEFI.TD_SOLICITUD_TOMO_II s,
     SIPEFI.TD_REL_LIC_ASIGNATURA rla,
     VALOR_PRACTICO, SEMESTRE, COLOR cl
WHERE l.ID_LICENCIATURA = :id_licenciatura
  and a.ID_ASIGNATURA = :id_asignatura
  and s.ID_SOLICITUD = a.ID_ASIGNATURA
  and s.HISTORICA = 0
  and rla.ID_LICENCIATURA = :id_licenciatura
  and rla.ID_SOLICITUD = :id_asignatura
  and ar.ID_AREA_CONOCIMIENTO = rla.id_area_conocimiento
  and m.ID_MODALIDAD =  s.ID_MODALIDAD
  and tm.ID_TIPO_MODALIDAD = s.ID_TIPO_MODALIDAD
  and c.ID_CARACTER_ASIG = rla.id_caracter_asig
  and cl.id = rla.id_area_conocimiento