with HORAS AS (
    select t.ID_SOLICITUD ID_HORAS, sum(t.HORAS_TEMA) HORAS_SUM
    from SIPEFI.TD_TEMARIO_ASIGNATURA t
    where t.ID_SOLICITUD = :id_asignatura
    group by t.ID_SOLICITUD
)
SELECT h.HORAS_SUM, s.ACTIVIDADES_PRACTICAS
from HORAS h, SIPEFI.TD_SOLICITUD_TOMO_II s
where s.ID_SOLICITUD = h.ID_HORAS
and s.HISTORICA = 0