WITH HORAS AS (
    SELECT t.ID_SOLICITUD AS ID_HORAS,
           SUM(t.HORAS_TEMA) AS HORAS_SUM
      FROM SIPEFI.TD_TEMARIO_ASIGNATURA t
      INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
        ON s.ID_SOLICITUD = t.ID_SOLICITUD
       AND s.ID_ESTATUS_SOLICITUD = t.ID_ESTATUS_SOLICITUD
     WHERE t.ID_SOLICITUD = :id_asignatura
       AND s.HISTORICA = 0
       AND s.ID_ESTATUS_SOLICITUD <> 0
     GROUP BY t.ID_SOLICITUD
)
SELECT h.HORAS_SUM,
       s.ACTIVIDADES_PRACTICAS
  FROM HORAS h
  INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
    ON s.ID_SOLICITUD = h.ID_HORAS
 WHERE s.HISTORICA = 0
   AND s.ID_ESTATUS_SOLICITUD <> 0
