with HORAS AS (
    select t.ID_SOLICITUD ID_HORAS, sum(t.HORAS_TEMA) HORAS_SUM
    from SIPEFI.TD_TEMARIO_ASIGNATURA t, SIPEFI.TD_SOLICITUD_TOMO_II s
    where t.ID_SOLICITUD = :id_asignatura
    and s.ID_SOLICITUD = t.ID_SOLICITUD
    and s.ID_ESTATUS_SOLICITUD = t.ID_ESTATUS_SOLICITUD
    and s.HISTORICA = 0
    group by t.ID_SOLICITUD
)
SELECT h.HORAS_SUM, s.ACTIVIDADES_PRACTICAS
from HORAS h, SIPEFI.TD_SOLICITUD_TOMO_II s
where s.ID_SOLICITUD = h.ID_HORAS
and s.HISTORICA = 0