SELECT DISTINCT
       ct.NUM_TEMA,
       ct.NUM_CONTENIDO AS id_contenido,
       ct.CONTENIDO
  FROM SIPEFI.TD_CONTENIDO_TEMATICO ct
  INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
    ON s.ID_SOLICITUD = ct.ID_SOLICITUD
   AND s.ID_ESTATUS_SOLICITUD = ct.ID_ESTATUS_SOLICITUD
 WHERE ct.ID_SOLICITUD = :id_asignatura
   AND s.HISTORICA = 0
   AND s.ID_ESTATUS_SOLICITUD <> 0
 ORDER BY ct.NUM_TEMA, ct.NUM_CONTENIDO
