WITH ANTECEDENTE AS (
    SELECT LISTAGG(DISTINCT a.ASIGNATURA, ', ')
           WITHIN GROUP (ORDER BY a.ASIGNATURA) AS seriacion_antecedente
      FROM SIPEFI.TD_ASIGNATURA a
      INNER JOIN SIPEFI.TD_REL_LIC_ASIGNATURA rel
        ON rel.SERIACION_ANT = a.ID_ASIGNATURA
      INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
        ON s.ID_SOLICITUD = rel.ID_SOLICITUD
       AND s.ID_ESTATUS_SOLICITUD = rel.ID_ESTATUS_SOLICITUD
     WHERE rel.ID_LICENCIATURA = :id_licenciatura
       AND rel.ID_SOLICITUD = :id_asignatura
       AND s.HISTORICA = 0
       AND s.ID_ESTATUS_SOLICITUD <> 0
),
CONSECUENTE AS (
    SELECT LISTAGG(DISTINCT a.ASIGNATURA, ', ')
           WITHIN GROUP (ORDER BY a.ASIGNATURA) AS seriacion_consecuente
      FROM SIPEFI.TD_ASIGNATURA a
      INNER JOIN SIPEFI.TD_REL_LIC_ASIGNATURA rel
        ON rel.SERIACION_CONS = a.ID_ASIGNATURA
      INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
        ON s.ID_SOLICITUD = rel.ID_SOLICITUD
       AND s.ID_ESTATUS_SOLICITUD = rel.ID_ESTATUS_SOLICITUD
     WHERE rel.ID_LICENCIATURA = :id_licenciatura
       AND rel.ID_SOLICITUD = :id_asignatura
       AND s.HISTORICA = 0
       AND s.ID_ESTATUS_SOLICITUD <> 0
)
SELECT a.seriacion_antecedente,
       c.seriacion_consecuente
  FROM ANTECEDENTE a
 CROSS JOIN CONSECUENTE c
