SELECT DISTINCT
       t.NUM_TEMA,
       t.TEMA,
       t.HORAS_TEMA,
       t.OBJETIVO
  FROM SIPEFI.TD_TEMARIO_ASIGNATURA t
  INNER JOIN SIPEFI.TD_SOLICITUD_TOMO_II s
    ON s.ID_SOLICITUD = t.ID_SOLICITUD
   AND s.ID_ESTATUS_SOLICITUD = t.ID_ESTATUS_SOLICITUD
 WHERE t.ID_SOLICITUD = :id_asignatura
   AND s.HISTORICA = 0
   AND s.ID_ESTATUS_SOLICITUD <> 0
 ORDER BY t.NUM_TEMA
