SELECT b.ID_BIBLIOGRAFIA_FC,
       b.ES_COMPLEMENTARIA,
       b.ID_TIPO_BIBLIOGRAFIA,
       tb.TIPO_BIBLIOGRAFIA,
       b.AUTOR,
       b.PUBLICACION,
       b.TITULO,
       b.CAMPO_1,
       b.CAMPO_2,
       b.CAMPO_3,
       b.CAMPO_4
  FROM SIPEFI.TD_BIBLIO_FORMACION_COMP b
  LEFT JOIN CATALOGO.TC_TIPO_BIBLIOGRAFIA tb
    ON tb.ID_TIPO_BIBLIOGRAFIA = b.ID_TIPO_BIBLIOGRAFIA
 WHERE b.ID_FORMACION = :id_formacion
 ORDER BY b.ID_BIBLIOGRAFIA_FC
