SELECT CASE
           WHEN r.ID_ESTRATEGIA_DIDACT IS NOT NULL THEN 1
           ELSE 0
       END AS SELECCIONADA,
       e.ID_ESTRATEGIA_DIDACT,
       e.ESTRATEGIA_DIDACTICA
  FROM CATALOGO.TC_ESTRATEGIAS_DIDACTICAS e
  LEFT JOIN SIPEFI.TD_REL_FC_ESTRATEGIA r
    ON r.ID_FORMACION = :id_formacion
   AND r.ID_ESTRATEGIA_DIDACT = e.ID_ESTRATEGIA_DIDACT
 WHERE e.ID_ESTRATEGIA_DIDACT > 0
 ORDER BY e.ID_ESTRATEGIA_DIDACT
