SELECT fc.ID_FORMACION,
       fc.ID_ESTATUS_FC,
       efc.DESC_ESTATUS,
       fc.CLAVE_ASIGNATURA,
       fc.NOMBRE_ASIGNATURA,
       fc.ID_AREA_CONOCIMIENTO,
       ac.AREA_CONOCIMIENTO,
       fc.SEMESTRE,
       mfc.MODALIDAD,
       tm.TIPO_MODALIDAD,
       ca.CARACTER_ASIGNATURA,
       fc.HORAS_PRACT_SEMANA,
       fc.HORAS_PRACT_SEMESTRE,
       fc.OBJETIVO_GENERAL,
       fc.JUSTIFICACION_ACADEMICA,
       fc.FECHA_CREACION,
       fc.FECHA_MODIFICACION,
       fc.FECHA_COMPLETADA
  FROM SIPEFI.TD_FORMACION_COMPLEMENTARIA fc
  INNER JOIN CATALOGO.TC_ESTATUS_FC efc
    ON efc.ID_ESTATUS_FC = fc.ID_ESTATUS_FC
  INNER JOIN CATALOGO.TC_AREA_CONOCIMIENTO ac
    ON ac.ID_AREA_CONOCIMIENTO = fc.ID_AREA_CONOCIMIENTO
  INNER JOIN CATALOGO.TC_MODALIDAD_FC mfc
    ON mfc.ID_MODALIDAD_FC = fc.ID_MODALIDAD_FC
  INNER JOIN CATALOGO.TC_TIPO_MODALIDAD tm
    ON tm.ID_TIPO_MODALIDAD = fc.ID_TIPO_MODALIDAD
  INNER JOIN CATALOGO.TC_CARACTER_ASIGNATURA ca
    ON ca.ID_CARACTER_ASIG = fc.ID_CARACTER_ASIG
 WHERE fc.ID_FORMACION = :id_formacion
   AND fc.ID_USUARIO_CREACION = :id_usuario
